---
title: "week-8-lab-homework"
author: "Adi Kantawala"
date: "March 1, 2017"
output: html_document
---

```{r}

housing <- read.csv("~/Desktop/Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])
hist(housing$Home.Value)

library(ggplot2)
ggplot(housing, aes(x = Home.Value)) +
  geom_histogram()

plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "red"),
       pch=c(1, 1))

ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()

#help.search("geom_", package = "ggplot2")

hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point()

ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point()

hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))

p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth()

p1 + 
  geom_text(aes(label=State), size = 3)

#install.packages("ggrepel") 
library("ggrepel")
p1 + 
  geom_point() + 
  geom_text_repel(aes(label=State), size = 3)

p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red

p1 +
  geom_point(aes(color=Home.Value, shape = region))

dat <- read.csv("~/Desktop/Rgraphics/dataSets/EconomistData.csv")

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point()

ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(color = "blue")

ggplot(dat, aes(x = CPI, y = HDI, color)) + geom_point()
unique(dat$Region)

ggplot(dat, aes(x = CPI, y = HDI, color = Region)) + geom_point(size=2)

ggplot(dat, aes(x = CPI, y = HDI, color = Region, size = HDI.Rank)) + geom_point()

```

```{r}
args(geom_histogram)
args(stat_bin)

p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()

p2 + geom_histogram(stat = "bin", binwidth=4000)

housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))

ggplot(housing.sum, aes(x=State, y=Home.Value)) + geom_bar()

ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
  geom_bar(stat="identity")

#exercise 2 


ggplot(dat, aes(x = CPI, y = HDI)) + geom_point()

ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() + geom_smooth()

ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() + geom_smooth(method = lm)

ggplot(dat, aes(x = CPI, y = HDI)) + geom_point() + geom_line(stat = "ecdf")

```

```{r}
p3 <- ggplot(housing,
             aes(x = State,
                 y = Home.Price.Index)) + 
        theme(legend.position="top",
              axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)))

p4 + scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"))

p4 +
  scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")

p4 +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")

p4 +
  scale_color_gradient2(name="",
                        breaks = c(1976, 1994, 2013),
                        labels = c("'76", "'94", "'13"),
                        low = "blue",
                        high = "red",
                        mid = "gray60",
                        midpoint = 1994)

#exercise 3

ex3plot <- ggplot(dat, aes(x = CPI, y = HDI), scale_y_continuous("Human Development Index")) + geom_point(aes(color= Region))
ex3plot

ex3plot <- ex3plot + scale_x_continuous(name = "Corruption perception index") + scale_y_continuous(name= "Human development index") + scale_fill_manual(name= "Region", breaks= c("Americas", "Asia Pacific", "East EU Cemt Asia", "EU W. Europe", "MENA", "SSA", labels = c("1", "2", "3", "4", "5", "6")))
ex3plot

ex3plot <- ggplot(dat, aes(x = CPI, y = HDI), scale_y_continuous("Human Development Index")) + geom_point(aes(color= Region))
cols <- c("tan", "red", "brown", "green", "orange", "purple")
ex3plot <- ex3plot + scale_color_manual(values = cols)
ex3plot
```

```{r}
p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))

(p5 <- p5 + geom_line() +
   facet_wrap(~State, ncol = 10))

p5 + theme_linedraw()

p5 + theme_light()

p5 + theme_minimal() +
  theme(text = element_text(color = "turquoise"))

theme_new <- theme_bw() +
  theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"),
        text=element_text(size = 12, family = "Serif", color = "ivory"),
        axis.text.y = element_text(colour = "purple"),
        axis.text.x = element_text(colour = "red"),
        panel.background = element_rect(fill = "pink"),
        strip.background = element_rect(fill = "orange"))

p5 + theme_new

library(tidyr)
home.land.byyear <- gather(housing.byyear,
                           value = "value",
                           key = "type",
                           Home.Value, Land.Value)
ggplot(home.land.byyear,
       aes(x=Date,
           y=value,
           color=type)) +
  geom_line()
```